name: 'Deploy to Firebase Cloud Functions for Pruvo Backend'
author: 'victorftrdba <victornogu80@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Cloud Functions on Pruvo Backend'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'black'
